### PR TITLE
Improve help for one key don't working

### PR DESCRIPTION
**Pull request by razzeee**
I had success with this on my board and tbh, seeing the bodge wire being recommended that fast, kinda made me panic.

### CODE REVIEW

**Review by burkfers — APPROVED** [review]

**Comment by burkfers** [comment]
Recommending less drastic action first is good, I agree.

nb: Even if you do need a bodge wire, there's no need to panic. There's plenty of bodges in the wild and the boards are no less beautiful :)

**Comment by razzeee** [comment]
I guess, still it's not that appealing to have to do a bodge, when you just got a new board that should work fine :)

**Comment by bstiq** [comment]
Made it more verbose, thoughts?

**Review by burkfers — APPROVED** [review]
`:kuzco_nice:`

**Comment by bstiq** [comment]
Thanks razzeee!

**Comment by razzeee** [comment]
waaay better, the only thing I'm still not happy with is `right switch leg` and never having talked about from which side you are looking to figure out where the right is.

**Comment by bstiq** [comment]
This is something that can be figured through schematics or multimeter, so I'm fine with it

**Comment by razzeee** [comment]
As long as there is no danger in doing that. But I would have liked to be sure, that I've tested the correct right leg when I reached out for help etc

**Comment by burkfers** [comment]
The assembly guides also view the PCBs from the component side at all times. I think "right leg" is precise enough here.

**Pull request merged**
