### PR TITLE
preference-sensing persistent dark mode toggle

### LINKED ISSUE #1: Dark theme
Add a toggle for dark theme
Justthedocs supports a default dark scheme: https://just-the-docs.com/docs/customization/#custom-schemes

I'd like to rework it a bit to have it a bit more "on brand" - have to figure out which colors work best.

They also support dynamic theme switching : https://just-the-docs.com/docs/customization/#switchable-custom-scheme
So we'd have to add a button somewhere on the page

Idea: add it to the top right as a moon logo, and replace the "BK on github" text by a github logo

### PR DESCRIPTION
**Pull request by burkfers**
Both light and dark stylesheets are loaded.
If the local storage item is present, that theme is applied.
If it is not present, one style is applied based on browser-supplied preference by means of css `@media` and light or dark is saved in local storage.
The button toggles the style immediately and saves the preference in local storage, overriding the browser-supplied preference.

### CODE REVIEW

**Comment by burkfers** [comment]
The callout colors need to be adjusted for the dark theme. I've made them explicit for your tweaking pleasure, see `assets/css/just-the-docs-bkb-dark.scss`.

**Comment by burkfers** [comment]
A little prettier: The color scheme toggle and the github aux link are now images.

**Comment by bstiq** [comment]
Great work here. 
As far as we can see visually everything looks good.
Let me know if you're also happy with the current code. If no more background work is needed I'll merge the PR.

**Comment by burkfers** [comment]
Only the issue that the toggle is not shown in mobile view remains, which I've broken out into #3.

Since we also respect the preference supplied by the browser, the selected view should be correct most of the time. Imho, the benefits of merging this now outweigh the drawback of possibly locking mobile users into a theme they didn't want.

**Pull request merged**
